### ISSUE TITLE
Support job throttling

### ISSUE THREAD

**Issue by gabbard** [isi-vista/vista-pegasus-wrapper#11]
See https://pegasus.isi.edu/documentation/job_throttling.php

**Comment by spigo900** [comment]
@LichMaster98 I'd like to use this for the MICS task I'm working on. Do you/did Ryan have any particular interface for this in mind?

For my use case I'd particularly like to restrict the number of jobs running at one time on the MICS project partition, but only a subset of the jobs will need to use that partition. So my idea is to allow (1) setting the job's category (as referenced in the documentation above), and (2) somehow set job throttling for that category, either in the config (like [right here](https://github.com/isi-vista/vista-pegasus-wrapper/blob/93f3c78d9b747e4ae7a138e01ee52b1aaae51a74/pegasus_wrapper/workflow.py#L238)) or in the DAX.

**Comment by LichMaster98** [comment]
@spigo900 No we didn't have an interface in mind -- If you'd like to add this feature to the repository and then have either myself or @joecummings review I believe we're currently the active maintainers of this support repository for the VISTA group.

Perhaps we should automatically categorize jobs based on the partition in the SLURM cluster the job is set to run in, providing a way to override that default, and then have a way to set a number of active jobs for that category by modifying that created conf file as you point out? 

I'm free to answer questions to help out in development if I can in some way!

**Comment by gabbard** [comment]
At BBN we allowed you to throttle by regular expressions over the job names, which allowed pretty fine-grained control.
