### ISSUE TITLE
Saga Cluster: Update PEGASUS_HOME

### ISSUE THREAD

**Issue by elizlee** [isi-vista/vista-pegasus-wrapper#110]
The Pegasus 5.0.0 installation has been removed (https://github.com/isi-vista/saga-cluster/issues/778)
https://github.com/isi-vista/vista-pegasus-wrapper/blob/bbc220bb9aa6adaaad1df785b51526b6d4b0fafc/pegasus_wrapper/pegasus_utils.py#L79

**Comment by lichtefeld** [comment]
@elizlee Is a reasonable solution to simply not set the `PEGASUS_HOME` value and let whatever the system default suffice or do we need to implement some logic to point to the `PEGASUS_HOME` directory dynamically based on the submit host the user is running this script from?

**Comment by elizlee** [comment]
@lichtefeld Finding the system default sounds like the better solution
