### ISSUE TITLE
Use Pegasus's own checkpoint handling

### ISSUE THREAD

**Issue by gabbard** [isi-vista/vista-pegasus-wrapper#23]
A common pattern when building workflows is that you discover problems after a partial run which requires modification of the compute graph.  Here's an example of how this might work from this repository:

1. Run https://github.com/isi-vista/gaia-event-extraction/blob/master/gaia_event_extraction/pegasus/argument_attachment/argument_attachment_pipeline.py on https://github.com/isi-vista/gaia-event-extraction/blob/master/sample_params/argument_attachment/pegasus/bilstm_gold_mentions.params . This generates a `Workflow.dax`. This also populates what we will call our "experiment directory", whose path is given by parameters to the DAX generation script.  This experiment directory has a sub-directory for each "artifact" created in the course of the experiment execution, which typically corresponds to one job.  The are often (but don't have to be) arranged in a hierarchy which partly reflects the computation graph.  Each artifact sub-directory contains:
   - - a `___run.sh` which is what is actually submitted to the cluster. It sets up a virtual environment and executes the program.
   - a `__params.params` which contains the param file passed to the program 
2. `pegasus-plan -d Workflow.dax  --dir $HOME/workflows --relative-dir aa-full-run0001` . `--dir` should point to something in your home directory, rather than on `/nas/gaia`, because otherwise it crashes for some NFS-related reason.  This specifies the root directory under which what we will call "Pegasus run directories" live. We'll generate a new one of these each time we run Pegasus with a substantially different DAX.  The name of the Pegasus run directory for a given run is given by `--relative-dir`.
3. `pegasus-run  /nas/home/gabbard/workflows/aa-full-run0001` . This actually executes the workflow.  As each job finishes, a `__ckpt` file is written to the corresponding artifact folder in the experiment directory.  You can monitor the workflow with `pegasus-status -l /nas/home/gabbard/workflows/aa-full-run0001 -w 10`.  
4. Suppose the workflow crashes and you need to make a substantial change to how you build the DAX in order to fix it.  The problem I was running into which motivated the introduction of `__ckpt` files is that if you edit your DAX generation script in a way which causes the generated DAX to diverge too much, then an attempt to run `pegasus-plan` with the same Pegasus run directory caused a crash. However, if you ran it with a new run directory, it would repeat everything which had already been executed successfully on the previous run.  In our current approach, the DAX generation script will [detect if a `__ckpt` file is present for a job](https://github.com/isi-vista/vista-pegasus-wrapper/blob/master/pegasus_wrapper/workflow.py#L149). If so, it will not include it in the newly generated DAX and you will be able to continue with the steps below.
5. `pegasus-plan` again, but this time with a new run directory: ``pegasus-plan -d Workflow.dax  --dir $HOME/workflows --relative-dir aa-full-run0002` (note the new `relative-dir`). Then continue with `pegasus-status`, etc. 

The additional advantage of using `__ckpt` files is that it's not uncommon for us to have several workflows we wish to run independently which share sub-structures. For example, imagine I have one set of experiments which requires running BERT on all of Gigaword, which is very time consuming.  I might then have a second set of experiments which takes that as input and does something else with it. With this method, I can reuse the data from one to another even though they have totally independent DAXes.

There are some disadvantages: the user has to manage them by hand, which provides flexibility but also the chance for errors.  More importantly, it ties us to running from a shared filesystem, which limits our ability of using some of Pegasus's neat features like helping us automatically shift data around to run on e.g. AWS.

To ultimately drop the reliance on a shared filesystem, we need to be able to use Pegasus `File` objects for our inputs and outputs. However, Pegasus by default is set up expecting the input and output files to be specified as job arguments.  We would need to have a way of interpolating *the local path* to a file transferred by Pegasus on the execution machine into the parameter file ultimately passed to our executing script.  That's it's own issue.  For this issue, one of the Pegasus developers suggested that as a baby step we make the `___ckpt` files themselves Pegasus `File`s.  A job would depend on the `File`s corresponding the the checkpoint files of its "parent" jobs and its output would always be the `File` corresponding to its own `checkpoint`.  

I believe this would require modifying the `DependencyNode` class to wrap Pegasus files and also altering the generated `run.sh`s so that they write the checkpoint files *locally to the compute node* and then have them transferred back by Pegasus.

**Comment by LichMaster98** [comment]
As discussed in #31 data reuse is handled by having a replica catalog established. Currently, the easiest way for us to do this is to build a `rc.txt` file which acts as our replica catalog where the only relevant files are our created checkpoint files. 

To implement this when the workflow generation tool is run, it will check to see if an output checkpoint file exists at the target location given by the param files for the workflow to process in. If the file exists, then following the format as [described here](https://pegasus.isi.edu/documentation/replica.php#rc-FILE) add an entry to the `rc.txt` file located in the submission directory. 

The `rc.txt` file will be rebuild each time the workflow generation tool is run. Meaning users submitting jobs to pegasus should run this tool each time before job submission to check for existing checkpoint files.
