### ISSUE TITLE
Pegasus Replica Catalog

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/vista-pegasus-wrapper#31]
Pegasus handles data discovery through a [replica catalog](https://pegasus.isi.edu/documentation/replica.php)

It appears we would need to maintain one of these to track the outputs of a previous workflow to allow for [data reuse](https://pegasus.isi.edu/documentation/mapping_refinement_steps.php#planning_data_reuse) 

However, the replica catalog doesn't actually do any verification that the physical file path (PFP) of a logical file name (LFN) exists when it goes to plan out the workflow. It appears this needs to be managed externally. 

There are several options for maintaining a replica catalog the easiest (and the default) is just to use a `rc.txt` file in the directory where `pegasus-plan` is expected to be run. 

Given this we could either modify our DAX generation script to account for this and see if the PFP of the files exist on the NAS, but that would limit the script's functionality to only implement data reuse given our shared file system -- and by person unless we can find a way around the NFS related bug.

**Comment by joecummings** [comment]
Can this be closed now that we are correctly using a `rc.dat` file to checkpoint? @LichMaster98

**Comment by LichMaster98** [comment]
@joecummings I think so
