### ISSUE TITLE
Enable restricting jobs to specific compute nodes in SLURM cluster

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/vista-pegasus-wrapper#50]
Also, might make sense to be able to specify nodes you DO want to run on as a follow-up PR. I know sometimes I want to specify a node that I'm sure has the right specifications.

_Originally posted by @joecummings in https://github.com/isi-vista/vista-pegasus-wrapper/pull/49#issuecomment-671472157_

**Comment by hassanzadeh** [comment]
I'm not sure Slurm has an option for this. there is --nodelist but the purpose is different. There is a --partition I'm not sure yet whether it can be helpful. Will research it though.

**Comment by LichMaster98** [comment]
I believe this paragraph:
> -w, --nodelist=<host1,host2,... or filename>
Request a specific list of hosts. The job will contain all of these hosts and possibly additional hosts as needed to satisfy resource requirements. The list may be specified as a comma-separated list of hosts, a range of hosts (host[1-5,7,...] for example), or a filename. The host list will be assumed to be a filename if it contains a "/" character. If you specify a minimum node or processor count larger than can be satisfied by the supplied host list, additional resources will be allocated on other nodes as needed. Rather than repeating a host name multiple times, an asterisk and a repetition count may be appended to a host name. For example "host1,host1" and "host1*2" are equivalent. If number of tasks is given and a list of requested nodes is also given the number of nodes used from that list will be reduced to match that of the number of tasks if the number of nodes in the list is greater than the number of tasks. This option applies to job and step allocations.

From https://slurm.schedmd.com/srun.html is what we would want to specify here? The other option is having a list of all possible slurm nodes by name and taking in a list of valid nodes to run the jobs on and building an exclude list to exclude everything but the targeted nodes. However, the second option requires us to maintain an active list of nodes, which means pushing an update here every time new machines are added. So that's not as eloquent of a solution.

**Comment by hassanzadeh** [comment]
Not really, the first one is not doing what you expect. The first one takes ALL the specified nodes, not ONE from them. "The job will contain all of these hosts and possibly additional hosts". The second approach might work, however, as you said it will be a quite ad-hoc approach. I can implement it though if it makes sense to do so.

**Comment by LichMaster98** [comment]
Hm, ok. @marjorief Do you have thoughts on this feature then? I'm hesitant to want to add something that requires an update every time new machines are added to the cluster, especially when partitions are the ideal way to limit compute to specific machines or making resource requests which put you on machines which can respect those requests.

**Comment by marjorief** [comment]
i tend to agree @LichMaster98 -- @hassanzadeh a way to improve this would be to invert the logic and as the user to specify the machines they are willing to use. It is a little more work for the user, but less work for the TBD maintainer :)

**Comment by hassanzadeh** [comment]
@marjorief I'm not sure I understood, are you in favor of the second approach (i.e. loading a predefined list of nodes and compute exclude list), or you mean we just leave it as is?

**Comment by marjorief** [comment]
I was confused, I'm not in favor of anything that would require the wrapper to be updated every time a node is added :). 

This may mean that there isn't a good way to support @joecummings request. A possibility would be to enable requesting a single using -nodelist as @LichMaster98 suggested.  For @joecummings use case (debugging), that might work.

**Comment by hassanzadeh** [comment]
Alright, in that case, I can go ahead and add the option, and update the document so that users know that --nodelist is only applicable when one you want to run a pipeline on a SINGLE node. Does that sound reasonable? Perhaps we should use a better name for the argument such as --run-on-single-node

**Comment by LichMaster98** [comment]
If the current desired use case is for debugging I think we could implement the `-w` solution and just include documentation that indicates that feature is intended for debugging use only and not in a production workflow?

**Comment by hassanzadeh** [comment]
Yep.

**Comment by hassanzadeh** [comment]
This is done. 
The two mutually exclusive options are:
run_on_single_node: node_name
exclude_nodes: node_names
