### ISSUE TITLE
Package for PyPi release

### ISSUE THREAD

**Issue by joecummings** [isi-vista/vista-pegasus-wrapper#52]
Leaving this as an issue for something to do down the line

**Comment by LichMaster98** [comment]
@joecummings My plan for the conclusion of the Upgrade to Pegasus5.0 is to make a publication to PyPi with this python library. 

@marjorief -- Other than myself and @joecummings are there others who should have the rights to update the PyPi package?

**Comment by marjorief** [comment]
also @danielnapierski , maybe @spigo900

**Comment by LichMaster98** [comment]
@joecummings, @danielnapierski, and @spigo900 -- What is your user name for [PyPi](https://pypi.org/) ? I'd like to add you as maintainers to the Pegasus-Wrapper package.

**Comment by danielnapierski** [comment]
`danielnapierski`

**Comment by spigo900** [comment]
`joececil`

**Comment by LichMaster98** [comment]
Invites have been sent to all individuals listed for the [pypi release of pegasus-wrapper](https://pypi.org/project/pegasus-wrapper/) -- That closes out this issue.
