### ISSUE TITLE
SAGA cluster is going to start enforcing a new account type for Scavenge and Ephemeral Usage

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/vista-pegasus-wrapper#67]
See: https://github.com/isi-vista/saga-cluster/issues/462#issuecomment-724991117 for the relevant information on this upcoming change.

Our wrapper will break when this change is officially enforced.

**Comment by marjorief** [comment]
@LichMaster98 -- how hard is the update to the wrapper?

**Comment by LichMaster98** [comment]
@marjorief  I'm suspecting this fix is very quick: https://github.com/isi-vista/vista-pegasus-wrapper/blob/master/pegasus_wrapper/resource_request.py#L189-L193 this section of code would just need to be updated to provide the correct account declaration when a scavenge or ephemeral QoS is provided.

**Comment by joecummings** [comment]
@LichMaster98 If I'm reading this correctly, that string just needs an added `--account=borrowed` right?

**Comment by LichMaster98** [comment]
Correct @joecummings We just need to coordinate the change in this repository to match whenever SAGA makes this change.
