### ISSUE TITLE
Allow user to specify partition to run specific job on

### ISSUE THREAD

**Issue by joecummings** [isi-vista/vista-pegasus-wrapper#69]
Scavenge and ephemeral are great for running a lot of shorter tasks, but others (like training a large model) require more time. Would be ideal to run most of preprocessing, decoding, and scoring on a borrowed partition, but throw training on a project-specific partition so that it has more time to run.

**Comment by spigo900** [comment]
Isn't this already possible? I think I used this in my MICS workflow. You can specify the partition as part of the SLURM resource request, which you can pass explicitly when you run a job.

**Comment by joecummings** [comment]
Oof not enough coffee this morning - you're right, this should work. I'll test real quick and close.
