### ISSUE TITLE
Typo in conda_job_script.py

### ISSUE THREAD

**Issue by jamart28** [isi-vista/vista-pegasus-wrapper#7]
https://github.com/isi-vista/vista-pegasus-wrapper/blob/80f9f12b91692cb52305152dc84b088e8eba6634/pegasus_wrapper/conda_job_script.py#L84
should be:
```python
spack_lines=self.spack_config.sbatch_lines(), 
```

**Comment by jamart28** [comment]
Pushed commit that fixes this to #6

**Comment by LichMaster98** [comment]
Closed via: https://github.com/isi-vista/vista-pegasus-wrapper/pull/10
