### ISSUE TITLE
Saga Cluster: Determine appropriate location to have pegasus installed for `PEGASUS_HOME` in properties file

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/vista-pegasus-wrapper#71]
@danielnapierski & @marjorief  Currently Pegasus for uses of `PEGASUS_HOME` in our properties is stored under Matts' home directory. This is an unsustainable long-term location given the transition to v5.0.0 its a good time to evaluate a better location for this install. The location needs to be somewhere on the NAS so all the submit nodes have access to it. Ideally, a shared location that's not anyone specific home dir would be better does either of you have a recommendation on where this location should be?

**Comment by danielnapierski** [comment]
@LichMaster98 @marjorief These is `/nas/gaia/shared/cluster` 
Perhaps we could create a `pegasus5` directory there.

Currently that directory has: 
```
├── drivers
├── spack
└── spack_mirror
```

**Comment by marjorief** [comment]
sounds good to me.

**Comment by danielnapierski** [comment]
Directory is now created.

```
$ pwd
/nas/gaia/shared/cluster/pegasus5
$ ls -ahl
total 8.0K
drwxr-xr-x 2 root gaia_users 4.0K Jan 12 07:43 .
drwxr-xr-x 6 root gaia_users 4.0K Jan 12 07:43 ..
```

@LichMaster98

**Comment by LichMaster98** [comment]
@danielnapierski Thanks! I'm going to close out this issue then.

**Comment by LichMaster98** [comment]
@danielnapierski I don't have the permissions to be able to install Pegasus 5.0.0 into this directory. The installation instructions from a tarball for Pegasus 5.0.0 can be found [at this link](https://pegasus.isi.edu/docs/5.0.0/user-guide/installation.html#pegasus-from-tarballs) the following will download the correct tarball for cluster and unzip it to hopefully the right directory.

```
wget http://download.pegasus.isi.edu/pegasus/5.0.0/pegasus-binary-5.0.0-x86_64_rhel_7.tar.gz
tar zxf pegasus-binary-5.0.0-x86_64_rhel_7.tar.gz -C /nas/gaia/shared/cluster/pegasus5
```

Additionally, I believe the configuration listed on this [part of the pegasus documentation](https://pegasus.isi.edu/docs/5.0.0/user-guide/execution-environments.html?highlight=glite#example-installation-on-a-rhel-7-login-node) regarding configuration for using a cluster will also need to be completed.

Seeing as I think some of these steps may require permissions on the cluster I don't have can I hand off these installation steps to you? It may also be wise of us to double-check with the Pegasus Team that we are configuring our installation correctly as I believe they configured out v4.9.3 installation for us.

**Comment by danielnapierski** [comment]
@LichMaster98  I update the permissions for that directory as it was missing 'write' for the 'gaiausers' group.  
`chmod g=rwx /nas/gaia/shared/cluster/pegasus5`
I did the tar extraction to that directory that you described above:
```
$ tree -d /nas/gaia/shared/cluster/pegasus5 -L 2
/nas/gaia/shared/cluster/pegasus5
└── pegasus-5.0.0
    ├── bin
    ├── etc
    ├── lib64
    └── share
```

**Comment by LichMaster98** [comment]
Closing issue as this has been taken care of now
