### ISSUE TITLE
Should this wrapper support ISI's donut cluster?

### ISSUE THREAD

**Issue by lichtefeld** [isi-vista/vista-pegasus-wrapper#83]
@marjorief -- I recall seeing emails about a new cluster, also slurm managed, that ISI is hosting at large called "Donut" does it make sense to support adding this as a submission site for this wrapper or is it reasonable to assume anyone using this wrapper from ISI will have access to VISTA's SAGA cluster?

I only ask because, theoretically, supporting the Donut cluster is as simple as adding a function to include "donut" as a compute site.

**Comment by marjorief** [comment]
I think if a user from the Donut cluster asks us, we can share but I'd avoid getting into the position of supporting this for all of ISI.  And I don't think Donut has installed Pegasus yet :)
