### ISSUE TITLE
False "jobs won't start" error message

### ISSUE THREAD

**Issue by joecummings** [isi-vista/vista-pegasus-wrapper#91]
`{workflow_name}.exitcode.log` shows the missing jobs as failing because `.//00/0{X}/{job_name}_{job_id}.out` does not exist. The user has confirmed that these files do not indeed exist; however, they should be automatically generated by a running job. It should be noted that the user had restarted the workflow multiple times, but only generated the workflow once. 

Other notes:
* The workflow directory is in my home directory (`/nas/home/jcecil/pegasus_working/.../compare_models`)
* spack is set up to use the `/nas/material` install and corresponding package versions
* All jobs that ran, succeeded

**Comment by spigo900** [comment]
Regenerating and resubmitting got some of the jobs to run (the few missing model-training jobs) but not others (the ones that compare pairs of model outputs), which fail with the same error as above. I will contact Karan about this later today.

**Comment by spigo900** [comment]
It turned out the problem was that I was using `=` in my job names. Thanks very much to Karan for figuring this out.

@lichtefeld and I ran into this on ADAM before. This is common enough and confusing enough we should probably handle it. I made a separate issue for that: #92.
