### ISSUE TITLE
Conda script runs Python script twice

### ISSUE THREAD

**Issue by spigo900** [isi-vista/vista-pegasus-wrapper#98]
The Conda job script template is (in 0.2.0 at least) generating two lines to run the Python script. Example:

```sh
echo
echo `which python`
echo python -m ai2.stat_analysis /nas/home/jcecil/pegasus_working/mics/mf-jm-jc-leaderboard-paper/compare_models/stat_analysis/____params.params
python -m ai2.stat_analysis /nas/home/jcecil/pegasus_working/mics/mf-jm-jc-leaderboard-paper/compare_models/stat_analysis/____params.params 2>&1 | tee /nas/home/jcecil/pegasus_working/mics/mf-jm-jc-leaderboard-paper/compare_models/stat_analysis/___stdout.log


echo `which python`
echo python -m ai2.stat_analysis /nas/home/jcecil/pegasus_working/mics/mf-jm-jc-leaderboard-paper/compare_models/stat_analysis/____params.params
python -m ai2.stat_analysis /nas/home/jcecil/pegasus_working/mics/mf-jm-jc-leaderboard-paper/compare_models/stat_analysis/____params.params 2>&1 | tee /nas/home/jcecil/pegasus_working/mics/mf-jm-jc-leaderboard-paper/compare_models/stat_analysis/___stdout.log
```

The relevant line is [233](https://github.com/isi-vista/vista-pegasus-wrapper/blob/0f15d5cfff30325a477b1bfacfb354452c64b854/pegasus_wrapper/conda_job_script.py#L233). Because `PYTHON_JOB` is a [multiline string](https://github.com/isi-vista/vista-pegasus-wrapper/blob/0f15d5cfff30325a477b1bfacfb354452c64b854/pegasus_wrapper/conda_job_script.py#L239), we end up with a blank echo line, followed by two `PYTHON_JOB` blocks.

**Comment by lichtefeld** [comment]
@spigo900 -- Are you going to submit a PR to fix this or should I do so and then update the pypi version?

**Comment by spigo900** [comment]
@lichtefeld If you could, I'd appreciate it. If not I will probably get to it sometime tomorrow afternoon.
